### ISSUE TITLE
Review of the "Global Port Spillover Estimator" code

### ISSUE THREAD

**Issue by yahui-zhao** [datapartnership/red-sea-monitoring#13]
Many thanks for the great work! Here are some suggestions.

For Part I: "Estimating At-Risk Capacity of a Port Disruption (Metric Tons) by Country," the code is very clear and well-written, with no issues in the results.

For Part II: "Estimating Aggregated At-Risk Export Value by Country from Any Port Disruption in a Selected Country (USD)," it is suggested only to select rows where "industry" equals "Total" when filtering data. This is to avoid the issue of double counting. Due to this oversight, the correct results should be exactly half of the current findings.

Thank you again!

**Comment by Holly-Transport** [comment]
Resolved - thank you.
