### ISSUE TITLE
Remove `ACLED_KEY` from config

### ISSUE THREAD

**Issue by g4brielvs** [datapartnership/red-sea-monitoring#19]
Remove `ACLED_KEY` from [config](https://github.com/datapartnership/red-sea-monitoring/blob/main/src/red_sea_monitoring/config.py). The key must be revoked and reissued. Please see [this example on how to secure keys](https://worldbank.github.io/template/notebooks/nasa-apod.html).

**Comment by g4brielvs** [comment]
@SahitiSarva When you have the chance, could you please work on this issue?

**Comment by SahitiSarva** [comment]
Revoked the Token and removed it from logs
